-- Question: Write a SQL query that returns the customer id, total revenue generated by the customer, 
-- and the date of the first order placed by the customer, for customers who have placed orders. 
-- Sort the results by total revenue in descending order.

select o.customerid
        , sum(o.quantity * o.priceperunit) 
        , (select min(o1.order_date) from orders1 o1 where o1.customerid = o.customerid)
from orders1 o
group by customerid
order by sum(o.quantity * o.priceperunit) desc